### ISSUE TITLE
Can I use this dataset to publish academic papers?

### ISSUE THREAD

**Issue by ghost** [uml-marine-robotics/MassMIND#1]
Can I use this dataset to publish academic papers?

**Comment by ssnirgudkar** [comment]
Of course, it is meant for the research purpose. Please let me know how it goes or if you have any issues while using the dataset.

Thanks,
-Shailesh

**Comment by ghost** [comment]
We would like to cite this dataset in the paper to compare the models, only for academic research, not for commercial work.

**Comment by ssnirgudkar** [comment]
Sure, please go ahead. Thank you.
